apiVersion: apps/v1
kind: Deployment
metadata:
  name: mport
  labels:
    app: mport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mport
  template:
    metadata:
      labels:
        app: mport
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      containers:
      - name: mt
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: svcmport
  namespace: default
spec:
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
    - name: mt
      port: 9002
      targetPort: 8080
  type: ClusterIP
  selector: 
    app: mport

