- name: Install vector
  hosts: vector
  tasks:
      - name: Upload tar.gz vector from remote URL
        get_url:
            url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
            dest: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
            mode: 0755
            timeout: 60
            force: true
            validate_certs: false
        register: get_vector
        until: get_vector is succeeded
        tags: vector
      - name: Create directrory for vector
        file:
          state: directory
          path: "{{ vector_home }}"
        tags: vector
      - name: Extract vector in the installation directory
        unarchive:
          copy: false
          src: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
          dest: "{{ vector_home }}"
          extra_opts: [--strip-components=1]
          creates: "{{ vector_home }}/bin/vector"
        tags:
          - skip_ansible_lint
          - vector
