apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  namespace: default
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv1
