apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scvol
  namespace: default
spec:
  storageClassName: my-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi